env:
  contexts:
    - name: baseline
      urls:
        - http://host.docker.internal:5000
      excludePaths: []

  parameters:
    failOnError: true
    progressToStdout: true

jobs:

  - type: passiveScan-config
    parameters:
      enableTags: true
      maxAlertsPerRule: 10

  - type: spider
    parameters:
      url: http://host.docker.internal:5000
      maxDuration: 5

  - type: passiveScan-wait

  - type: report
    parameters:
      template: traditional-html
      reportDir: /zap/wrk/
      reportFile: zap-report.html
      reportTitle: ZAP GameStore Report